version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - my_network

volumes:
  mongodb-data:

networks:
  my_network:
    driver: bridge
